### ISSUE TITLE
"Caspion cannot be opened..." #MacOS #Big_Sur #M1

### ISSUE THREAD

**Issue by tbendr** [brafdlog/caspion#276]
# Caspion for mac
---
#### Does Caspion support M1 chips?
--------------------------
![CleanShot 2021-07-25 at 16 14 19](https://user-images.githubusercontent.com/60432141/126900557-c2d2a4b1-5d16-43d9-8c52-5f8e0e7e1b58.png)

**Comment by baruchiro** [comment]
@tbendr I have a new release to test on M1 before I will publish it. Do you want to try?

If so, please contact me inMail, it is a big file. baruchiro@gmail.com

**Comment by baruchiro** [comment]
@tbendr I understand the artifact is working?

**Comment by baruchiro** [comment]
Update: I created a "universal" artifact in #277, @tbendr tested it but now the `main` process loaded but there is no UI (`renderer process`). I'm waiting for the logs.

**Comment by hannanel100** [comment]
is this issue being worked on? i tried to to install dependencies via yarn and got an error: 
error /Users/hannanel/Documents/hannanel/caspion/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/hannanel/Documents/hannanel/caspion/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:520:28)
    at module.exports (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:640:26)
    at ClientRequest.emit (node:events:532:35)
    at ClientRequest.origin.emit (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)

after trying to implement the changes in PR #277  i got this error:

error /Users/hannanel/Documents/hannanel/caspion/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments: 
Directory: /Users/hannanel/Documents/hannanel/caspion/node_modules/electron-chromedriver
Output:
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:520:28)
    at module.exports (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:640:26)
    at ClientRequest.emit (node:events:532:35)
    at ClientRequest.origin.emit (/Users/hannanel/Documents/hannanel/caspion/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip',
    href: 'https://github.com/electron/electron/releases/download/v9.0.0/chromedriver-v9.0.0-darwin-arm64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
      statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
      errorCodes: Set(8) {
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      }
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Thu, 26 May 2022 07:45:13 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'permissions-policy': 'interest-cohort=()',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'transfer-encoding': 'chunked',
    'x-github-request-id': 'C326:12D59:1059F0:11D266:628F3009',
    connection: 'close

**Comment by baruchiro** [comment]
https://github.com/eshaham/israeli-bank-scrapers/issues/686

**Comment by baruchiro** [comment]
@hannanel100 @tbendr Please check https://github.com/brafdlog/caspion/releases/tag/v0.2.0 if it works on your M1.

**Comment by tbendr** [comment]
> @hannanel100 @tbendr Please check https://github.com/brafdlog/caspion/releases/tag/v0.2.0 if it works on your M1.

It does, Thanks!!

To open it you need to:
1. Download the .dmg file
2. open it and drag Caspion to the Application folder
3. Go to Application folder
4. Right click on Caspion, then "Open"
5. You will get a warning message about unverified developer -- Click "Cancel"
6. Go to System Preferences > Security & Privacy > General tab > click to lock on the left bottom corner and type your mac password
7. Click "Open Anyway" next to the line: _"caspion" was blocked from use because it is not from an
identified developer._
8. Open Caspion app again

**Comment by baruchiro** [comment]
Thanks @tbendr!

I will add it to the README file.

**Comment by baruchiro** [comment]
Closed by #378

**Comment by nkk1987** [comment]
Hey, 
There seems to be an issue with the DMG file. 
I'm trying to run it on macOS Sonoma 14.4.1 (23E224) (M1 Pro), and it results with an error:
"caspion.app" is damaged and can't be opened. You should move it to the Trash.
<img width="328" alt="image" src="https://github.com/brafdlog/caspion/assets/25200301/2cdfc996-828e-480d-8d8a-9646c254e1be">
Any idea?

**Comment by baruchiro** [comment]
I saw it too!

Now I know there is a problem.

Meanwhile, I installed the previous version.

**Comment by baruchiro** [comment]
What was only a warning for unsigned apps on the Intel chip became to be **a damaged app** on the Apple chip.

To sign it with an empty signature and get the warning back:

```
codesign --force --deep -s - caspion.app
```

Then, right-click on the app and select `Open` and you will need to approve the warning. You will need to do it only once (per version 😔)

I will keep this open until we will solve it.

Need to add the explanation above to the documentation.

**Comment by baruchiro** [comment]
I prefer to keep this open, we are still using the comments here.

**Comment by baruchiro** [comment]
> [הפקודה למאק](https://github.com/brafdlog/caspion?tab=readme-ov-file#mac-prerequisites) דורשת תיקון קטן
> 
> ```
> ariel@xxx ~ % sudo xattr -r -d com.apple.quarantine /Applications/caspion.app/
> Password:
> option -r not recognized
> 
> usage: xattr [-slz] file [file ...]
>        xattr -p [-slz] attr_name file [file ...]
>        xattr -w [-sz] attr_name attr_value file [file ...]
>        xattr -d [-s] attr_name file [file ...]
>        xattr -c [-s] file [file ...]
> 
> The first form lists the names of all xattrs on the given file(s).
> The second form (-p) prints the value of the xattr attr_name.
> The third form (-w) sets the value of the xattr attr_name to attr_value.
> The fourth form (-d) deletes the xattr attr_name.
> The fifth form (-c) deletes (clears) all xattrs.
> 
> options:
>   -h: print this help
>   -s: act on symbolic links themselves rather than their targets
>   -l: print long format (attr_name: attr_value)
>   -z: compress or decompress (if compressed) attribute value in zip format
> ```
> 
> כדי לתקן את הפקודה, צריך להוריד את ה **r-**  
> `sudo xattr -d com.apple.quarantine /Applications/caspion.app/`

_by @ariel-wiz on https://github.com/brafdlog/caspion/issues/620_

**Comment by baruchiro** [comment]
See this BTW
https://github.com/relagit/relagit/issues/22

**Comment by yerachw** [comment]
Tried installing on Tahoe 26.3.1. Could not find where to enable Capion according to this link: https://github.com/brafdlog/caspion/issues/276#issuecomment-1282111297
