### ISSUE TITLE
Error: Attempted to register a second handler for 'showSaveDialog'

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#278]
From #276 logs, in Mac, if you close that app but Mac keeps it opened (don't understand this feature) we are getting this error:

```
[2021-07-29 20:19:19.814] [debug] Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (electron/js2c/browser_init.js:197:337)
    at /Applications/caspion.app/Contents/Resources/app-arm64.asar/background.js:2:577063
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (/Applications/caspion.app/Contents/Resources/app-arm64.asar/background.js:2:577041)
    at u (/Applications/caspion.app/Contents/Resources/app-arm64.asar/background.js:2:429830)
    at App.<anonymous> (/Applications/caspion.app/Contents/Resources/app-arm64.asar/background.js:2:430021)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:467:12)
```

[main.log](https://github.com/brafdlog/caspion/files/6908292/main.log)

**Comment by bablat** [comment]
I'm getting this on Ubuntu as well:

`[4031202:0220/132624.004944:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
(node:4031136) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `caspion --trace-deprecation ...` to show where the warning was created)
13:26:24.087 › Attempted to register a second handler for 'showSaveDialog'
13:26:24.088 › UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at /tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767131)
    at m (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6646721)
13:26:24.089 › UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at /tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767131)
    at m (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6646721)
(node:4031136) UnhandledPromiseRejectionWarning: UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at /tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6767131)
    at m (/tmp/.mount_caspiojJrJkZ/resources/app.asar/background.js:2:6646721)
(node:4031136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`
