### ISSUE TITLE
Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by SirAppSec** [brafdlog/caspion#463]
While installing the application for the first time, using Windows 11.
I get the following error:
`Failed to launch the browser process! spawn C:\Users\Amitx\AppData\Roaming\caspion\win64-843427\chrome-win\chrome.exe ENOENT TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md`
![image](https://user-images.githubusercontent.com/89794666/229100435-795feb37-58d6-41d7-b47c-cc5afaff1e8c.png)

From the [Puppeteer troubleshooting](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14):
`he most common cause is a bug in Node.js v14.0.0 which broke extract-zip, the module Puppeteer uses to extract browser downloads into the right place. The bug was fixed in Node.js v14.1.0`

Is there a way for me to update my node.js version?
Or is it the packaged electron that needs to be updated? assuming the issue would be resolved using Node.js v14.1.0

Note: Notice this happens in the Old UI, because New UI doesn't respond when clicking הפעל

**Comment by SirAppSec** [comment]
render.log
'''
[2023-03-31 11:35:46.432] [info]  Welcome to caspion log
[2023-03-31 11:35:46.434] [info]  Version: 1.11.4
[2023-03-31 11:35:46.801] [info]  Vue started
[2023-03-31 11:35:57.976] [info]  Starting to scrape from Sun Feb 19 2023 00:00:00 GMT+0000 (Greenwich Mean Time) to today
[2023-03-31 11:35:58.340] [info]  Download Chrome: 0%
[2023-03-31 11:35:59.332] [info]  Download Chrome: 1%
[2023-03-31 11:35:59.697] [info]  Download Chrome: 2%
[2023-03-31 11:36:00.058] [info]  Download Chrome: 3%
[2023-03-31 11:36:00.423] [info]  Download Chrome: 4%
[2023-03-31 11:36:01.093] [info]  Download Chrome: 5%
[2023-03-31 11:36:01.709] [info]  Download Chrome: 6%
[2023-03-31 11:36:02.355] [info]  Download Chrome: 7%
[2023-03-31 11:36:02.945] [info]  Download Chrome: 8%
[2023-03-31 11:36:03.331] [info]  Download Chrome: 9%
[2023-03-31 11:36:03.692] [info]  Download Chrome: 10%
[2023-03-31 11:36:04.060] [info]  Download Chrome: 11%
[2023-03-31 11:36:04.420] [info]  Download Chrome: 12%
[2023-03-31 11:36:04.782] [info]  Download Chrome: 13%
[2023-03-31 11:36:05.142] [info]  Download Chrome: 14%
[2023-03-31 11:36:05.504] [info]  Download Chrome: 15%
[2023-03-31 11:36:05.865] [info]  Download Chrome: 16%
[2023-03-31 11:36:06.230] [info]  Download Chrome: 17%
[2023-03-31 11:36:06.594] [info]  Download Chrome: 18%
[2023-03-31 11:36:06.955] [info]  Download Chrome: 19%
[2023-03-31 11:36:07.321] [info]  Download Chrome: 20%
[2023-03-31 11:36:07.683] [info]  Download Chrome: 21%
[2023-03-31 11:36:08.049] [info]  Download Chrome: 22%
[2023-03-31 11:36:08.528] [info]  Download Chrome: 23%
[2023-03-31 11:36:08.889] [info]  Download Chrome: 24%
[2023-03-31 11:36:09.298] [info]  Download Chrome: 25%
[2023-03-31 11:36:09.660] [info]  Download Chrome: 26%
[2023-03-31 11:36:10.025] [info]  Download Chrome: 27%
[2023-03-31 11:36:10.386] [info]  Download Chrome: 28%
[2023-03-31 11:36:10.748] [info]  Download Chrome: 29%
[2023-03-31 11:36:11.109] [info]  Download Chrome: 30%
[2023-03-31 11:36:11.470] [info]  Download Chrome: 31%
[2023-03-31 11:36:11.831] [info]  Download Chrome: 32%
[2023-03-31 11:36:12.210] [info]  Download Chrome: 33%
[2023-03-31 11:36:12.572] [info]  Download Chrome: 34%
[2023-03-31 11:36:12.934] [info]  Download Chrome: 35%
[2023-03-31 11:36:13.295] [info]  Download Chrome: 36%
[2023-03-31 11:36:13.769] [info]  Download Chrome: 37%
[2023-03-31 11:36:14.135] [info]  Download Chrome: 38%
[2023-03-31 11:36:14.495] [info]  Download Chrome: 39%
[2023-03-31 11:36:14.857] [info]  Download Chrome: 40%
[2023-03-31 11:36:15.220] [info]  Download Chrome: 41%
[2023-03-31 11:36:15.583] [info]  Download Chrome: 42%
[2023-03-31 11:36:15.976] [info]  Download Chrome: 43%
[2023-03-31 11:36:16.356] [info]  Download Chrome: 44%
[2023-03-31 11:36:16.722] [info]  Download Chrome: 45%
[2023-03-31 11:36:17.091] [info]  Download Chrome: 46%
[2023-03-31 11:36:17.454] [info]  Download Chrome: 47%
[2023-03-31 11:36:17.817] [info]  Download Chrome: 48%
[2023-03-31 11:36:18.183] [info]  Download Chrome: 49%
[2023-03-31 11:36:18.544] [info]  Download Chrome: 50%
[2023-03-31 11:36:19.020] [info]  Download Chrome: 51%
[2023-03-31 11:36:19.380] [info]  Download Chrome: 52%
[2023-03-31 11:36:19.742] [info]  Download Chrome: 53%
[2023-03-31 11:36:20.108] [info]  Download Chrome: 54%
[2023-03-31 11:36:20.469] [info]  Download Chrome: 55%
[2023-03-31 11:36:20.830] [info]  Download Chrome: 56%
[2023-03-31 11:36:21.191] [info]  Download Chrome: 57%
[2023-03-31 11:36:21.566] [info]  Download Chrome: 58%
[2023-03-31 11:36:21.928] [info]  Download Chrome: 59%
[2023-03-31 11:36:22.318] [info]  Download Chrome: 60%
[2023-03-31 11:36:22.679] [info]  Download Chrome: 61%
[2023-03-31 11:36:23.042] [info]  Download Chrome: 62%
[2023-03-31 11:36:23.403] [info]  Download Chrome: 63%
[2023-03-31 11:36:23.766] [info]  Download Chrome: 64%
[2023-03-31 11:36:24.249] [info]  Download Chrome: 65%
[2023-03-31 11:36:24.610] [info]  Download Chrome: 66%
[2023-03-31 11:36:24.972] [info]  Download Chrome: 67%
[2023-03-31 11:36:25.333] [info]  Download Chrome: 68%
[2023-03-31 11:36:25.739] [info]  Download Chrome: 69%
[2023-03-31 11:36:26.104] [info]  Download Chrome: 70%
[2023-03-31 11:36:26.465] [info]  Download Chrome: 71%
[2023-03-31 11:36:26.833] [info]  Download Chrome: 72%
[2023-03-31 11:36:27.196] [info]  Download Chrome: 73%
[2023-03-31 11:36:27.558] [info]  Download Chrome: 74%
[2023-03-31 11:36:27.920] [info]  Download Chrome: 75%
[2023-03-31 11:36:28.287] [info]  Download Chrome: 76%
[2023-03-31 11:36:28.648] [info]  Download Chrome: 77%
[2023-03-31 11:36:29.038] [info]  Download Chrome: 78%
[2023-03-31 11:36:29.483] [info]  Download Chrome: 79%
[2023-03-31 11:36:29.846] [info]  Download Chrome: 80%
[2023-03-31 11:36:30.221] [info]  Download Chrome: 81%
[2023-03-31 11:36:30.582] [info]  Download Chrome: 82%
[2023-03-31 11:36:30.943] [info]  Download Chrome: 83%
[2023-03-31 11:36:31.305] [info]  Download Chrome: 84%
[2023-03-31 11:36:31.672] [info]  Download Chrome: 85%
[2023-03-31 11:36:32.033] [info]  Download Chrome: 86%
[2023-03-31 11:36:32.400] [info]  Download Chrome: 87%
[2023-03-31 11:36:32.761] [info]  Download Chrome: 88%
[2023-03-31 11:36:33.123] [info]  Download Chrome: 89%
[2023-03-31 11:36:33.485] [info]  Download Chrome: 90%
[2023-03-31 11:36:33.846] [info]  Download Chrome: 91%
[2023-03-31 11:36:34.212] [info]  Download Chrome: 92%
[2023-03-31 11:36:34.575] [info]  Download Chrome: 93%
[2023-03-31 11:36:34.936] [info]  Download Chrome: 94%
[2023-03-31 11:36:35.298] [info]  Download Chrome: 95%
[2023-03-31 11:36:35.660] [info]  Download Chrome: 96%
[2023-03-31 11:36:36.072] [info]  Download Chrome: 97%
[2023-03-31 11:36:36.433] [info]  Download Chrome: 98%
[2023-03-31 11:36:36.909] [info]  Download Chrome: 99%
[2023-03-31 11:36:37.270] [info]  Download Chrome: 100%
[2023-03-31 11:38:38.973] [info]  Starting to scrape from Sun Feb 19 2023 00:00:00 GMT+0000 (Greenwich Mean Time) to today
[2023-03-31 11:38:40.657] [info]  Starting to scrape from Sun Feb 19 2023 00:00:00 GMT+0000 (Greenwich Mean Time) to today
'''

**Comment by SirAppSec** [comment]
general.log
```
[2023-03-31 11:31:39.584] [info]  Welcome to caspion log
[2023-03-31 11:31:39.587] [info]  Version: 1.11.4
[2023-03-31 11:31:39.787] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-03-31 11:31:39.788] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at m (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646721)
[2023-03-31 11:31:39.825] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at m (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646721)
[2023-03-31 11:35:44.908] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-03-31 11:35:44.908] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:35:44.909] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:35:45.894] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-03-31 11:35:45.895] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:35:45.895] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:36:04.028] [error] unexpected end of file
[2023-03-31 11:36:04.029] [debug] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:36:04.029] [error] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:36:04.029] [error] unexpected end of file
[2023-03-31 11:36:04.030] [debug] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:36:04.030] [error] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:39:48.289] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-03-31 11:39:48.290] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:39:48.290] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:39:50.707] [error] unexpected end of file
[2023-03-31 11:39:50.708] [debug] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:39:50.708] [error] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:42:00.041] [info]  Checking for update
[2023-03-31 11:42:00.049] [info]  Generated new staging user ID: ccc04b87-682f-50a5-90de-803a83f9d5e6
[2023-03-31 11:42:02.112] [info]  Update for version 1.11.4 is not available (latest version: 1.11.4, downgrade is disallowed).
[2023-03-31 11:44:35.383] [error] unexpected end of file
[2023-03-31 11:44:35.383] [debug] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:44:35.383] [error] Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
[2023-03-31 11:44:37.766] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-03-31 11:44:37.767] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
[2023-03-31 11:44:37.767] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767153
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6767131)
    at d (C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647193)
    at async C:\Users\Amitx\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6647568
```

**Comment by SirAppSec** [comment]
I found a workaround if someone has encountered the same issue:

1. go to download the latest chromium, for me it was [this](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/1124624/) . But use the [following link](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/). to find the latest chrome release look for the file [LAST_CHANGE](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2FLAST_CHANGE?generation=1680257145594258&alt=media)
2. download and extract chrome-win.zip
3. in the Caspion application use the settings and provide the path to chrome: C:\Users\<USERNAME>\Downloads\Win_x64_1124624_chrome-win\chrome-win\chrome.exe
Make sure to replace <USERNAME> with your windows username.

**Comment by baruchiro** [comment]
I think we are using the latest `v14` version, as you can see here:
https://github.com/brafdlog/caspion/actions/runs/4061787331/workflow#L42

I will try to upgrade the node version anyway.
