### ISSUE TITLE
Attempted to register a second handler for 'showSaveDialog'

### ISSUE THREAD

**Issue by eran-barkai** [brafdlog/caspion#478]
## Details
        
עבד עד אתמול, פתאום הפסיק, בלוג מופיע השגיאה המצורפת, כמו כן ניסיון של הורדת גרסא 1.19 -> 1.18 כמו גם מחיקות (הכל למעט המקודד כשל). המחשב מריץ ווינדוס 10 המופע היחיד אצלכם של הבאג הזה ב MAC M1 

```
[2023-05-28 13:45:51.916] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768931
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768909)
    at m (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646963)
```
## Log
```
        [2023-05-28 13:18:59.986] [info]  Version: 1.11.9
[2023-05-28 13:19:00.135] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-05-28 13:19:00.139] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768931
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768909)
    at m (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646963)
[2023-05-28 13:19:00.141] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768931
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768909)
    at m (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646963)
[2023-05-28 13:45:51.782] [info]  Welcome to caspion log
[2023-05-28 13:45:51.785] [info]  Version: 1.11.8
[2023-05-28 13:45:51.914] [error] Attempted to register a second handler for 'showSaveDialog'
[2023-05-28 13:45:51.915] [debug] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768931
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768909)
    at m (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646963)
[2023-05-28 13:45:51.916] [error] UnhandledRejection Error: Attempted to register a second handler for 'showSaveDialog'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
    at C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768931
    at Array.forEach (<anonymous>)
    at Object.t.registerHandlers (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6768909)
    at m (C:\Users\thund\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6646963)
```

## System Info
        
- Source Version: `937c9d658ea7af280724dfcd02002857d5a00e7e`
- OS: `browserjavascript`
- OS Version: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.11.8 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by brafdlog** [comment]
@eran-barkai 
מה בדיוק הפסיק לעבוד?
השגיאה שצירפת קרתה עד עכשיו בלי לפגוע בריצה של התוכנה

**Comment by eran-barkai** [comment]
> @eran-barkai מה בדיוק הפסיק לעבוד? השגיאה שצירפת קרתה עד עכשיו בלי לפגוע בריצה של התוכנה

יכול להיות שזאת לא השגיאה שגורמת לבעיה אבל לחיצה על הפעל פשוט מדלגת על הבאת הדאטה לחלוטין וקופצת ישר ליצירת גוגל שיט. ניסיתי לשנמך גרסא, ניסיתי הסרת כל הקבצים למעט המידע המקודד של החשבונות.. לא נראה שעוזר
