### ISSUE TITLE
After the last upgrade the scraper starts trying to import to YNAB without first scraping

### ISSUE THREAD

**Issue by ikrascloudinary** [brafdlog/caspion#511]
Tried to reinstall and set up from scratch with no luck.

![Nov-27-2023 09-27-40](https://github.com/brafdlog/caspion/assets/77568000/2833fbb1-83aa-46f0-87b4-7d5eeee6c0a7)

**Comment by baruchiro** [comment]
Please open the "דיווח על בעיה" modal, and you will see the location of the logs there:

![image](https://github.com/brafdlog/caspion/assets/17686879/5c5c0637-82b1-4cdf-b0ec-f122ac896c4e)

**Comment by ikrascloudinary** [comment]
@baruchiro @brafdlog logs from the latest run

```
[2023-12-20 09:44:57.333] [info]  Welcome to caspion log
[2023-12-20 09:44:57.339] [info]  Version: 1.13.1
[2023-12-20 09:45:06.383] [error] {"error":{"id":"401","name":"unauthorized","detail":"Unauthorized"}}
[2023-12-20 09:45:06.383] [debug] UnhandledRejection: {"error":{"id":"401","name":"unauthorized","detail":"Unauthorized"}}
    at process.o (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7779022)
    at process.emit (node:events:390:28)
    at process.emit (node:domain:475:12)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:237:9)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
[2023-12-20 09:45:06.384] [error] UnhandledRejection: {"error":{"id":"401","name":"unauthorized","detail":"Unauthorized"}}
    at process.o (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7779022)
    at process.emit (node:events:390:28)
    at process.emit (node:domain:475:12)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:237:9)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

```

**Comment by ikrascloudinary** [comment]
Tried installing it from scratch on another machine and it works. guess something is messed up on mine. But removing the app and reinstalling on my machine didn't work.

How can I completely remove everything on a Mac @baruchiro?

**Comment by baruchiro** [comment]
I don't know, I don't have a Mac right now.
Google it please 🙏

**Comment by brafdlog** [comment]
> @baruchiro @brafdlog logs from the latest run

@ikrascloudinary 
Sorry for the delay in response.
Interesting, you are getting unauthorized for something, that would mean either the bank you are trying to access or ynab.
Does the call to ynab end successfully? If so, the 401 is probably from the bank.
Have you tried scraping with the browser visible? This sometimes allows you to see the source of the issue (you can set browser to be visible or not in the settings)

**Comment by brafdlog** [comment]
> Tried installing it from scratch on another machine and it works. guess something is messed up on mine. But removing the app and reinstalling on my machine didn't work.
> 
> How can I completely remove everything on a Mac @baruchiro?

The configuration files and other state, are stored on a mac in:
`/Users/<Your user>/Library/Application Support/caspion`

You can delete the app from applications, remove that folder and then reinstall

**Comment by ikrascloudinary** [comment]
Thanks so much @brafdlog. Removed the folder you suggested and reinstalled, works again! 🙏
