### ISSUE TITLE
לא מצליח להוריד מידע ממזרחי

### ISSUE THREAD

**Issue by grooverATR** [brafdlog/caspion#523]
## Details
        
לא מצליח להוריד מידע ממזרחי
## Log
```
[2023-12-22 01:20:16.621] [info]  Welcome to caspion log
[2023-12-22 01:20:16.636] [info]  Version: 1.18.0
[2023-12-22 01:20:25.845] [info]  Checking for update
[2023-12-22 01:20:28.768] [info]  Update for version 1.18.0 is not available (latest version: 1.18.0, downgrade is disallowed).
[2023-12-22 01:30:00.773] [info]  Checking for update
[2023-12-22 01:30:02.907] [info]  Update for version 1.18.0 is not available (latest version: 1.18.0, downgrade is disallowed).
[2023-12-22 01:32:35.068] [error] Insufficient Permission
[2023-12-22 01:32:35.069] [debug] UnhandledRejection Error: Insufficient Permission
    at t.Gaxios._request (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6982829)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u.requestAsync (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:278787)
    at async Object.t.getSheet (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6495048)
    at async Object.exportTransactions (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:1029350)
    at async C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6813989
    at async Promise.all (index 1)
    at async Object.t.createTransactionsInExternalVendors (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6814377)
    at async Object.t.scrapeAndUpdateOutputVendors (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6809215)
[2023-12-22 01:32:35.070] [error] UnhandledRejection Error: Insufficient Permission
    at t.Gaxios._request (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6982829)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u.requestAsync (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:278787)
    at async Object.t.getSheet (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6495048)
    at async Object.exportTransactions (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:1029350)
    at async C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6813989
    at async Promise.all (index 1)
    at async Object.t.createTransactionsInExternalVendors (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6814377)
    at async Object.t.scrapeAndUpdateOutputVendors (C:\Users\אהרן\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6809215)
 
```
## System Info
        
- Source Version: `e1dad7e1b061660bc7608b4ea0acea9ed5903d47`
- OS: `browserjavascript`
- OS Version: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.18.0 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by baruchiro** [comment]
I'm not sure what the problem is here, but let's wait for this: https://github.com/eshaham/israeli-bank-scrapers/pull/821

**Comment by baruchiro** [comment]
I think this issue is solved.
