### ISSUE TITLE
הזנת נתונים לגוגל שיטס חדש לא עובד

### ISSUE THREAD

**Issue by evvanida** [brafdlog/caspion#535]
## Details
        
מחקתי את קובץ גוגל שיטס מכיוון שכותרות העמודות בו נמחקו. אני מנסה להריץ את האפליקציה כדי שיווצר קובץ חדש אבל זה רץ לעד בלי תוצאות. בנוסף, כשאני מנסה לקבוע שם לקובץ גוגל שיטס השם לא נשמר.
## Log
```
[2024-02-09 18:28:25.528] [info]  Checking for update
[2024-02-09 18:28:28.173] [info]  Update for version 1.20.1 is not available (latest version: 1.20.1, downgrade is disallowed).
[2024-02-09 18:28:34.719] [info]  Welcome to caspion log
[2024-02-09 18:28:34.723] [info]  Version: 1.20.1
[2024-02-09 18:41:15.973] [error] Requested entity was not found.
[2024-02-09 18:41:15.975] [debug] UnhandledRejection Error: Requested entity was not found.
    at t.Gaxios._request (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6982829)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u.requestAsync (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:278787)
    at async Object.t.getSheet (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6495048)
    at async Object.exportTransactions (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:1029350)
    at async C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6813989
    at async Promise.all (index 0)
    at async Object.t.createTransactionsInExternalVendors (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6814377)
    at async Object.t.scrapeAndUpdateOutputVendors (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6809215)
[2024-02-09 18:41:15.975] [error] UnhandledRejection Error: Requested entity was not found.
    at t.Gaxios._request (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6982829)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u.requestAsync (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:278787)
    at async Object.t.getSheet (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6495048)
    at async Object.exportTransactions (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:1029350)
    at async C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6813989
    at async Promise.all (index 0)
    at async Object.t.createTransactionsInExternalVendors (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6814377)
    at async Object.t.scrapeAndUpdateOutputVendors (C:\Users\adina\AppData\Local\Programs\caspion\resources\app.asar\background.js:2:6809215)
[2024-02-09 18:44:00.130] [info]  Welcome to caspion log
[2024-02-09 18:44:00.135] [info]  Version: 1.20.1
 
```
## System Info
        
- Source Version: `0b5242b1bc8963f4db34c89fa823c9989a38fa62`
- OS: `browserjavascript`
- OS Version: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.20.1 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by baruchiro** [comment]
Hi, we need to check it. Hope we will find a time soon.

Meanwhile I'm inviting you to our [Discord Channel](https://discord.gg/5UDEZ3Bz) where you can discuss with more users and see if someone find a way to work around the problem.
