### ISSUE TITLE
A JavaScript error occurred in the browser process

### ISSUE THREAD

**Issue by Shai2u** [brafdlog/caspion#564]
## Details
        
```
   Error
at /Applications/caspion.app/Contents/
Resources/app.asar/ background.js:2:6554041
at FSReqCallback.oncomplete
(node:fs:198:21)
```

## Log
```
at /Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7307046
    at async Object.d [as scrapeFinancialAccountsAndFetchTransactions] (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7265082)
    at async Object.t.scrapeAndUpdateOutputVendors (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:6809136)
[2024-06-14 07:10:08.544] [error] UnhandledRejection TypeError: Cannot destructure property 'executablePath' of 'undefined' as it is undefined.
    at /Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7307046
    at async Object.d [as scrapeFinancialAccountsAndFetchTransactions] (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:7265082)
    at async Object.t.scrapeAndUpdateOutputVendors (/Applications/caspion.app/Contents/Resources/app.asar/background.js:2:6809136)
[2024-06-14 07:10:19.525] [info]  Welcome to caspion log
[2024-06-14 07:10:19.527] [info]  Version: 1.27.1
```

## System Info
        
- Source Version: `57312d9727f99fd79a13e19cc75110a9e1675a9f`
- OS: `browserjavascript`
- OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.27.1 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by baruchiro** [comment]
It failed to download the browser.

This issue is discussed in [our Discord channel](https://discord.gg/XWWg7xvJyS), please join.
