### ISSUE TITLE
Isracard failing to scrape

### ISSUE THREAD

**Issue by D3SL** [brafdlog/caspion#609]
**Describe the bug**
Isracard fails with an error about passwords.

**To Reproduce**
Run Caspion 2.1.3 with an Isracard account

**Expected behavior**
Download Isracard transactions

**Screenshots**
![image](https://github.com/user-attachments/assets/1d042329-088a-4ea6-841c-e939464deb27)

**Additional context**
When running with the scraper window visible the problem appears to be at Isracard's login, where you need to choose between a password or non-password login. The scraper reaches that pages and then fails to progress.

This could be something on Isracard's website. Password input using bitwarden also fails, the password must be typed manually by hand or Isracard won't recognize it as valid.

**Comment by shaiu** [comment]
@D3SL works for me
I see in the logs here INVALID_PASSWORD so please check your password

@baruchiro @brafdlog this can be closed

**Comment by D3SL** [comment]
> I see in the logs here INVALID_PASSWORD

That's the bug. The password is completely valid. I've even tried multiple resets and clean installs, including less secure passwords without any non-alphanumeric characters. I can log in just fine manually on Isracard's website. It's either the bank scraper or caspion that's failing. 

>works for me

Screenshots on the discord show it doesn't work for other people as well. If it works for you but not multiple other people that suggests to me environmental contamination. You're a maintainer for the project, there may be development artifacts contaminating your environment that the rest of us don't have.

**Comment by shaiu** [comment]
@D3SL ok I understand.
Can you attach more logs?
You can find them in the "report a problem" section

**Comment by D3SL** [comment]
I have two theories: 
1. The Isracard website seems to get stuck at the point where it needs to change from entry via SMS to entry with a password (screenshot below). 
2. When I use a password manager to autofill login information on Isracard's website the password is rejected as invalid with the error "יש להזין 8-20 ספרות ואותיות באנגלית" even though there are no special characters. I can only log in if I physically type in the password by hand. 


![image](https://github.com/user-attachments/assets/d36d346c-469d-49af-9e74-5f914a92a0a4)



```
    at un (file:///C:/Users/redacted/AppData/Local/Programs/caspion/resources/app.asar/packages/main/dist/index.js:761:13)
[2024-11-05 10:10:06.263] [info]  (main) Welcome to caspion log
[2024-11-05 10:10:06.266] [info]  (main) Version: 2.1.3
[2024-11-05 10:10:06.267] [info]  (main) Logs folder: C:\Users\redacted\AppData\Roaming\caspion\logs
[2024-11-05 10:10:06.381] [info]  (main) Checking for update
[2024-11-05 10:10:06.762] [info]  (renderer) Welcome to Caspion log
[2024-11-05 10:10:06.763] [info]  (renderer) Version: <need implementation>
[2024-11-05 10:10:06.763] [info]  (renderer) Frontend started
[2024-11-05 10:10:06.819] [error]            (node:27940) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `caspion --trace-deprecation ...` to show where the warning was created)
[2024-11-05 10:10:06.830] [error]            (node:27940) Warning: Use Cipheriv for counter mode of aes-256-ctr
[2024-11-05 10:10:08.347] [info]  (main)     Update for version 2.1.3 is not available (latest version: 2.1.3, downgrade is disallowed).
[2024-11-05 10:10:08.348] [debug] (main)     checkForUpdatesAndNotify called, downloadPromise is null
[2024-11-05 10:10:22.827] [error]            (node:27940) Warning: Use Cipheriv for counter mode of aes-256-ctr
[2024-11-05 10:10:27.001] [info]  (main)     Scraping financial accounts and fetching transactions
[2024-11-05 10:10:27.002] [info]  (main)     Using provided chromium path C:\Users\super\AppData\Roaming\caspion\chromium\chrome.exe
[2024-11-05 10:10:32.819] [error] (main)     Failed to fetch transactions Error: INVALID_PASSWORD: undefined
    at un (file:///C:/Users/redacted/AppData/Local/Programs/caspion/resources/app.asar/packages/main/dist/index.js:761:13)
[2024-11-05 10:10:40.656] [error] (main)     Failed to fetch transactions Error: CHANGE_PASSWORD: undefined
    at un (file:///C:/Users/redacted/AppData/Local/Programs/caspion/resources/app.asar/packages/main/dist/index.js:761:13)
```

**Comment by baruchiro** [comment]
If there is a problem with the scraper itself, you need to report it to `israeli-bank-scrapers`

Look at this please:
https://github.com/eshaham/israeli-bank-scrapers/issues/883

**Comment by D3SL** [comment]
I'm not sure if it's Caspion or the Scrapers. I have this with fully alphanumeric passwords (`[a-zA-Z0-9]` only).

**Comment by D3SL** [comment]
No idea what changed but it works now in 2.4.0. I think this may actually be in Isracard's end because now their website doesn't give me the error when trying to input passwords with a manager like bitwarden, all I have to do is delete and retype the last letter/digit of the password by hand.

**Comment by baruchiro** [comment]
Thank you

**Comment by baruchiro** [comment]
איזה באג מעצבן.

קרה לי גם כן משהו מוזר הפעם, הנה מה שהם כותבים בהחלפת סיסמה:

<img width="637" alt="image" src="https://github.com/user-attachments/assets/4592b615-d485-4072-a2b2-1390b6abfbe9">

אין הסבר. תהמרו

**Comment by MusiCode1** [comment]
Listen, Isracard's website is problematic.
It doesn't make sense that we're doing QA for them...

Anyway, thanks to whoever wrote not to use special characters in the password.
I've always struggled with bitwarden, and I couldn't figure out where the problem is (apart from the general insight that Isracard has a problem with the QA department).
Now because it says not to use special characters here, I tried it, and both bitwarden and Caspion worked great!
Thanks.

(Translated with Google Translate. What's wrong with you, we're in Israel, and the users are Israeli... and I don't know English)

**Comment by D3SL** [comment]
ואני לא יודע programming בעברית. האם זה היה באמת הכרחי להעליב אותי כי אני עולה שלא יכול לדבר על הנושא הזה בעברית?

**Comment by MusiCode1** [comment]
Sorry, I apologize.
סליחה, אני מתנצל.

**Comment by D3SL** [comment]
תודה. חוץ מזה אני לא חולק עלך. ישראכרט לא ישנה את האתר שלהם אז בכל אופן הבעיה שלנו בסוף.
רק לברר דבר אחד: ההודעה באתר שלהם על "special characters" זה שקר. הסיסמה שלי היה אותיות ומספרים ועדיין לא עבד.

**Comment by baruchiro** [comment]
ההודעה שלהם לא מספיק מפורטת, מה שדורש מאיתנו לחקור מה בדיוק הבעיה.

(וכל אחד יכתוב בשפה שנוח לו, אנחנו זורמים כרגע. בדיסקורד למשל מדברים בעברית)
